---

- name: install EPEL package
  yum:
    name: "{{ epel_baseurl }}/epel-release-latest-7.noarch.rpm"
    state: present

- name: correct the EPEL repo file
  template:
    src: "{{ item }}.j2"
    dest: "/etc/yum.repos.d/{{ item }}"
    mode: u=rw,g=r,o=r
    owner: root
    group: root
  loop:
    - 'epel.repo'
    - 'epel-testing.repo'

