---
# tasks file for packages

- name: configure the proxy for YUM
  ini_file:
    path: /etc/yum.conf
    section: main
    option: proxy
    value: "{{ proxy }}"
    no_extra_spaces: yes
  when:
    - proxy is defined

- name: install the Satellite client certificate and key
  copy:
    src: "{{ local_satellite_client_cert }}"
    dest: "{{ satellite_client_cert }}"
  when:
    - satellite_client_cert is defined
    - local_satellite_client_cert is file

- name: enable/disable SCL repository on RedHat
  rhsm_repository:
    name: "{{ rhscl_repo }}"
    state: "{{ additional_packages_scl is defined | ternary('enabled','disabled') }}"
  ignore_errors: yes
  when:
    - ansible_distribution == "RedHat"

- name: enable/disable SCL repository on CentOS
  package:
    name: centos-release-scl
    state: "{{ additional_packages_scl is defined | ternary('present','absent') }}"
  when:
    - ansible_distribution == "CentOS"

- name: enable EPEL repository
  import_tasks: epel.yml
  when: enable_epel

- name: install required packages
  yum:
    name: "{{ additional_packages | union(additional_packages_scl | default([])) }}"
    state: present
    update_cache: yes
    skip_broken: yes

- name: enable installed SCL packages
  copy:
    src: "etc/profile.d/scl-enable-{{ item }}.sh"
    dest: "/etc/profile.d/scl-enable-{{ item }}.sh"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  loop: "{{ additional_packages_scl }}"
  when:
    - additional_packages_scl is defined
    - ( role_path + '/files/etc/profile.d/scl-enable-' + item + '.sh' ) is file

